### PR TITLE
1.2.0 -> staging

### LINKED ISSUE #255: if config fails to load, error should be logged
read_path() just swallows the error -- not found might be expected, other errors should be raised and cause the app to fail to launch

### LINKED ISSUE #265: NR error: "Undefined method '[]' for nil:NilClass" in QueryBuilder#search_location
[New Relic example](https://rpm.newrelic.com/accounts/1065766/applications/8349766/filterable_errors#/show/bb333c-9f75e7f4-b17d-11e5-9286-b82a72d2466d/stack_trace?top_facet=transactionUiName&primary_facet=error.class&_k=yibim9). Frequency: 16 times from Jan 1 to Jan 7.

Stack trace:
```ruby
NoMethodError: undefined method `[]' for nil:NilClass
         /home/vcap/app/lib/data_magic/query_builder.rb:  132:in `search_location'
         /home/vcap/app/lib/data_magic/query_builder.rb:   30:in `generate_squery'
         /home/vcap/app/lib/data_magic/query_builder.rb:   13:in `from_params'
                       /home/vcap/app/lib/data_magic.rb:   69:in `search'
                      /home/vcap/app/app/controllers.rb:   53:in `block (2 levels) in <top (required)>'
(eval):225:in `block in call'
(eval):214:in `catch'
```

Refers to [this line](https://github.com/18F/open-data-maker/blob/a5c5a18381214d3a51ab54152b463727bb3f79bc/lib/data_magic/query_builder.rb#L132): 
```ruby
squery = squery.geo('location', distance: distance, lat: location[:lat], lng: location[:lon])
```

### LINKED ISSUE #276: NR error: undefined method `each' for nil:NilClass in DataMagic.search
[New Relic error log](https://rpm.newrelic.com/accounts/1065766/applications/7790612/filterable_errors#/show/c5b584-592d21ab-c3b2-11e5-bb22-b82a72d2466d/stack_trace?top_facet=transactionUiName&primary_facet=error.class&_k=n4gixl). Error triggered by loading this URL on staging: https://ccapi-staging.18f.gov/v1/schools/stats?school.degrees_awarded.predominant=2,3&_fields=2013.student.size&_metrics=avg,std_deviation,std_deviation_bounds

I _think_ it's because the `school.degrees_awarded.predominant` field doesn't exist - so why isn't ErrorChecker trapping it?

Traceback:
```
NoMethodError: undefined method `each' for nil:NilClass
                       /home/vcap/app/lib/data_magic.rb:  142:in `search'
                      /home/vcap/app/app/controllers.rb:   69:in `search_and_respond'
                      /home/vcap/app/app/controllers.rb:   65:in `process_params'
                      /home/vcap/app/app/controllers.rb:   51:in `block (2 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by ultrasaurus**
- Move from Travis to Circle CI
- Update New Relic gem, so as to use the new Error Analytics features
- Upgrade puma to 2.15.3 so it builds on OS X 10.11 OK
- Fix various errors we're seeing in NewRelic:
  -    better zip/distance error reporting (fixes #265 and #266)
  -    stats on nested fields no longer throw a stack trace, but doesn't yet give correct result (#276)
- Remove obsolete RunRailsCops rubocop directive
- Document location field (#227)

### CODE REVIEW

**Comment by yozlet** [comment]
:shipit:
